apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "jenkins.fullname" . }}
  namespace: {{ include "jenkins.fullname" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "jenkins.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jenkins.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: jenkins_ROOT_PASSWORD
          value: adminpass
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ include "jenkins.fullname" . }}
        ports:
          - containerPort: {{ .Values.service.port }}
            name: http
            protocol: TCP
        volumeMounts:
          - mountPath: /var/{{ include "jenkins.fullname" . }}_home
            name: {{ include "jenkins.fullname" . }}
            readOnly: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: {{ include "jenkins.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "jenkins.fullname" . }}-volume
  podManagementPolicy: OrderedReady
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  serviceName: {{ include "jenkins.fullname" . }}
  updateStrategy:
    type: OnDelete