apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: uptime-local.kuberstar.com
  namespace: uptime-kuma
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`uptime-local.kuberstar.com`)
      services:
        - name: uptime-kuma
          port: 3001
  tls:
    certResolver: myresolver