# ArgoCD
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-local.kuberstar.com
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`argocd-local.kuberstar.com`)
      services:
        - name: argocd-server
          port: 80
---
# Traefik Dashboard
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-local.kuberstar.com
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik-local.kuberstar.com`)
      kind: Rule
      middlewares:
        - name: traefik-dashboard-basicauth
          namespace: traefik
      services:
        - name: api@internal
          kind: TraefikService
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-dashboard-basicauth
  namespace: traefik
spec:
  basicAuth:
    secret: traefik-dashboard-auth
---
# ArgoCD
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-local.kuberstar.com
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`grafana-local.kuberstar.com`)
      services:
        - name: grafana
          port: 80
---
# Longhorn
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-local.kuberstar.com
  namespace: longhorn
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`longhorn-local.kuberstar.com`)
      services:
        - name: longhorn-frontend
          port: 80
---
# Portainer
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: portainer-local.kuberstar.com
  namespace: portainer
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`portainer-local.kuberstar.com`)
      services:
        - name: portainer
          port: 9000
---
# Docker Registry
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: docker-registry-local.kuberstar.com
  namespace: docker-registry
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`docker-registry-local.kuberstar.com`)
      services:
        - name: docker-registry
          port: 5000
      middlewares:
        - name: docker-registry-auth
          namespace: docker-registry
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: docker-registry-auth
  namespace: docker-registry
spec:
  basicAuth:
    secret: docker-registry-auth