replicaCount: 1

image:
  repository: louislam/uptime-kuma
  pullPolicy: IfNotPresent

nameOverride: "uptime-kuma"
fullnameOverride: "uptime-kuma"

service:
  type: ClusterIP
  port: 3001
  targetPort: 3001
  clusterIP: 10.43.79.175

path:
  cluster: /app/data
