apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-dashboard-auth
  namespace: traefik
spec:
  encryptedData:
    users: AgBd6ZecToLbHRcfcl2lhdCddQdVQrSJMqIVk+iTIy+zAg9bMWQpXIopiDlMoMuGl/bzK2jaa0xLRb8rdzLkOoYfSjB1R+uCCKnqZN7lgAzp9olnPGnxicQ3Mi8t8a2IsIjlykQt17EDSQ/39yo7QHnVMO4H1ZqsSPZdIT1DNojwrGyq9fAjLFpiOEybpB1Dgj8wZY0eucsgNwiXfeC8oi1b646DLmuQNQFF/R3mFo5HRtkdMmH80ivpBjL70pvVpGjs3wcF2+mbrE8bupM4Mh3zL95/e7rKxLB6LqpOTVi8Nhmu4ufwU5Yi51v6KF4UE9Pua8mszsEn4ZDZtaUQ1GiMqJ6AqHh3jRlKeoIjzqFNVfCYJTQ4AMzsj2bxO0po0zTYkClQokDC09NgoIQ0beu0SWbq7YOH/Yp5ZWKOA1xq2SreE6R0CBI2U9Qsz6H5iWJPS6ND/72PpnA2NfG+8xnf2Ex8Eh4DBgNWcELEfIagiWS0Ro3wEQxXNyBIwrV86nH6bgSCbhL/pZ3Bc3SImgJQlK1kXuVDfhWdeeAHILZu5ORgJ4QFlvhXTHAdRoNJN8Na48cyvifwmlUvWvMxEJawfmLcLVmh2iDn++DJ5X0GqUhsUMZXLZ2+6PTKFWKpF30csDczt6n7p0V+SlkuI4up+EVtpPOWG9hC9bq6iwl8YapuhaGBCsEJrYyFVmdAo0hko/RoaaGuWnujbOiLtgfAyoTM9oxCIyqMkM0bei6ZAqwAEmKB+mMTA5x2Pws=